name: CI

on:
  schedule:
    - cron: '*/1 * * * *'
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: |
         echo " " >> README.md
         git config user.name redolf250
         git config user.email redolfkendrick@gmail.com
         git add .
         git commit -m "Always Green!"
         git push
